### ISSUE TITLE
Error during 'fin init' process 'Script "drupal-phpunit-upgrade" is not defined in this package'

### ISSUE THREAD

**Issue by init90** [docksal/drupal8-contrib#1]
After run `fin init` I have got next error:

Script `drupal-phpunit-upgrade` is not defined in this package

To fix it I have commented the next line: `composer run-script drupal-phpunit-upgrade` in the `.docksal/commands/init-site` file.

Also, similar problem described here:
https://www.drupal.org/node/3056978

**Comment by lmakarov** [comment]
@init90 thanks for reporting this.
`init-site` script has been updated and steps related to php-unit upgrade removed.
