### ISSUE TITLE
Comoser version problem

### ISSUE THREAD

**Issue by init90** [docksal/drupal8-contrib#3]
"Drupal core development requires Composer 1.9.0, but Composer 1.8.0 is installed. Please run 'composer self-update'."

We can update Composer based on instructions on the issue: https://github.com/docksal/docksal/issues/1126 

But I think it should work out of the box.

**Comment by lmakarov** [comment]
There are newer `docksal/cli` images available (v2.7.0+) which ship with Composer 1.9.0:
https://github.com/docksal/service-cli/releases/

The next release of Docksal will switch the default stack to use the new `cli` images. In the mean time, you can override the image version like this (assuming you are using a default stack - your projects `docksal.yml` only one line):

```
fin config set CLI_IMAGE=docksal/cli:2.8-php7.3
fin up
```

**Comment by lmakarov** [comment]
I did not realize this was not the main docksal/docksal repo. I will add the changes proposed above to this repo directly.
