### ISSUE TITLE
needs update to drupal 9

### ISSUE THREAD

**Issue by vacho** [docksal/drupal8-contrib#9]

**Comment by vacho** [comment]
maybe a new branch, or another repo.

**Comment by lmakarov** [comment]
@jhedstrom in case you are interested in porting this over for Drupal 9, the new repo is here and you should have access to commit into it :)
https://github.com/docksal/drupal9-contrib/settings/access

**Comment by jhedstrom** [comment]
Initial port is here https://github.com/docksal/drupal9-contrib/pull/1

Drush 8 seems incompatible with Drupal 9. We could install drush, but then folks would immediately have changed `composer.json` files in their contrib repo. I'll open an issue over in this new project so we can figure out what to do with regards to drush.

In the meantime, a manual install via the UI is working.

**Comment by jhedstrom** [comment]
Actually drush was working (on travis anyway.) That is merged now, closing this out. Thanks for the reminder this didn't work out of the box on d9!
